source 'http://rubygems.org'

gem 'eventmachine', :git => 'https://github.com/eventmachine/eventmachine.git'
gem 'em-http-request', :git => 'https://github.com/igrigorik/em-http-request.git'

gem 'yajl-ruby', :require => 'yajl'
gem 'em-stathat'
gem 'log4r'
gem 'test-unit'